[env]
platform = espressif32
board = esp32dev
framework = arduino
board_build.f_cpu = 240000000L
monitor_speed = 115200
lib_deps = kosme/arduinoFFT@1.6.0

[env:node2]
upload_port = COM12
build_flags = -DNODE_ID=2

[env:node3]
upload_port = COM11
build_flags = -DNODE_ID=3

[env:esp32dev]
upload_port = COM12
build_flags = -DNODE_ID=2
